#!/usr/bin/env python3

import reports
import emails
import json
import locale
import sys
import os

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
  max_revenue = {"revenue": 0}

  max_sales ={"max_sales": 0}
  popular_year = {}
  
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    #  also handle max sales 
    if item["total_sales"] > max_sales["max_sales"]:
      item["max_sales"] = item["total_sales"]
      max_sales = item
    
        # also handle most popular car_year
    year = item["car"]["car_year"]
    if year in popular_year :
      popular_year[year]["count"] += 1
      popular_year[year]["revenues"] += item["total_sales"]
    else:
      #initialize empty dic
      popular_year[year] = { "count": 1,
                            "revenues" : item["total_sales"] }
  #print(popular_year)
  # find best popular year
  pop_year= sorted(popular_year.items(), key=lambda kv: kv[1]["count"],reverse=True)
  #print(pop_year)

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),

      "The {} had the most sales: {}".format(
        format_car(max_sales["car"]), max_sales["max_sales"]),

        "The most popular year was {} with {} sales.".format(
          pop_year[0][0],
          pop_year[0][1]["revenues"]
        )

            ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data



def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  table_data = cars_dict_to_table(data)

  reports.generate("/tmp/cars.pdf", "Sales summary for last month", "<br/>".join(summary), table_data)



  # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = "\n".join(summary)

  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)

